# Generated by Django 5.1.2 on 2024-11-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='status',
            field=models.TextField(default='Stop'),
            preserve_default=False,
        ),
    ]
