# Generated by Django 5.1.2 on 2025-02-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_program_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Functions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func_name', models.TextField(max_length=100)),
                ('func_description', models.TextField(max_length=250)),
            ],
        ),
    ]
