# Generated by Django 5.1.2 on 2025-02-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_functions'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='ip_address',
            field=models.GenericIPAddressField(default='192.168.1.1'),
            preserve_default=False,
        ),
    ]
