# Generated by Django 5.1.2 on 2025-04-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_savedprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSocketIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_ip_address', models.TextField(max_length=20)),
            ],
        ),
    ]
