# Generated by Django 5.1.1 on 2025-04-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interface", "0007_savedprogram_program_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="code_templates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("value", models.TextField(default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
