# Generated by Django 5.2 on 2025-04-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0008_code_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.TextField(max_length=50)),
                ('file_name', models.TextField(max_length=50)),
            ],
        ),
    ]
